name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
      - dev
      - feature/*
      - release/*
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js with caching
      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      # Install all dependencies using monorepo script
      - name: Install Dependencies
        run: npm run install:all

      # Build both projects using monorepo script
      - name: Build Projects
        run: npm run build

      # Run tests for both projects using monorepo script
      - name: Run Tests
        run: npm test

      # Run linting for both projects using monorepo script
      - name: Run Linting
        run: npm run lint

      # Run type checking for both projects using monorepo script
      - name: Run Type Checking
        run: npm run check
