name: Cross-Platform Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - main
      - releases/*
      - dev
      - feature/*
      - release/*
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  NODE_VERSION: 22.x

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            coverage: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run check

      - name: Build projects
        run: npm run build

      - name: Run tests with coverage
        if: matrix.coverage
        run: npm run test:coverage

      - name: Run tests
        if: '!matrix.coverage'
        run: npm test

      - name: Upload coverage reports
        if: matrix.coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./graphql-server/coverage/lcov.info,./frontend/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            graphql-server/dist
            frontend/build
            frontend/.svelte-kit/output
          retention-days: 1
