name: deploy-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - dev
      - staging
      - test
      - main
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # - name: Get DynamoDB Item
      #   id: config
      #   uses: mooyoul/dynamodb-actions@v1.2.1
      #   env:
      #     AWS_DEFAULT_REGION: ${{ AWS_DEV_REGION }}
      #     AWS_REGION: ${{ AWS_DEV_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   with:
      #     operation: get
      #     region: ${{ AWS_DEV_REGION }}
      #     table: ${{ AWS_DEV_DYNAMODB_TABLE_NAME }}
      #     key: |
      #       { key: "gamePk" }
      - name: Print item
        # run: |
        #   # echo '${{ steps.config.outputs.item }}'
        run: |
          echo 'inside deploy'
      # - name: Print specific field using built-in function
      #   run: |
      #     echo '${{ fromJson(steps.config.outputs.item).commit }}'
      # - name: Print specific field using jq
      #   run: |
      #     jq '.commit' <<< '${{ steps.config.outputs.item }}'
